spring.application.name: kafka-streams-aggregate
spring.cloud.stream.bindings.input:
  destination: foobar
spring.cloud.stream.kafka.streams.binder:
  brokers: localhost #192.168.99.100
  configuration:
    default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    default.value.serde: org.apache.kafka.common.serialization.Serdes$BytesSerde
    commit.interval.ms: 1000